"""Signal Engine public API."""

from __future__ import annotations

from signal_engine.assembly.assembler import SignalAssembler
from signal_engine.candidates import DirectionCandidate
from signal_engine.contracts.assembly_request import SignalAssemblyRequest
from signal_engine.exceptions import (
    SignalAssemblyError,
    SignalEngineError,
    SignalIntakeError,
    SignalLLMAttachmentError,
    SignalMLAttachmentError,
    SignalNotFoundError,
    SignalRegistrationError,
    SignalRiskAttachmentError,
    SignalRuleError,
    SignalValidationError,
)
from signal_engine.indicators import (
    IndicatorComputationError,
    MACDResult,
    compute_atr,
    compute_macd,
    compute_rsi,
    compute_sma,
)
from signal_engine.intake import (
    FeatureIntakePayload,
    MarketIntakeFrame,
    SnapshotIntakeRef,
    feature_intake_from_set,
    feature_intake_from_store_record,
    feature_intake_from_vector,
    market_intake_from_candle,
    market_intake_from_record,
    provenance_from_intake,
    snapshot_ref_from_snapshot,
)
from signal_engine.lifecycle import SignalLifecycleService
from signal_engine.llm import (
    LLMInsightProvider,
    StubLLMInsightProvider,
    assert_safe_insight_text,
    attach_llm_insight,
    attach_llm_insight_from_provider,
    ensure_llm_insight_present,
    llm_insight_from_llm_response,
    llm_insight_from_parts,
)
from signal_engine.ml import (
    MLPredictionProvider,
    StubMLPredictionProvider,
    attach_ml_prediction,
    attach_ml_prediction_from_provider,
    ensure_ml_prediction_present,
    ml_prediction_from_inference_response,
    ml_prediction_from_normalized_output,
)
from signal_engine.registry.signal_record import SignalRecord
from signal_engine.registry.signal_registry import (
    SignalRegistry,
    get_signal_registry,
    reset_signal_registry,
)
from signal_engine.risk import (
    RiskBindingProvider,
    StubRiskBindingProvider,
    assert_directional_confidence,
    attach_confidence,
    attach_invalidation,
    attach_risk_assessment,
    attach_risk_bindings,
    attach_risk_bindings_from_provider,
    build_invalidation_rule,
    build_risk_assessment,
    confidence_value_from_score,
    ensure_risk_bindings_present,
    invalidation_from_atr,
    invalidation_from_structure,
)
from signal_engine.rules import (
    CandidateRule,
    RSIMACDRule,
    apply_candidate,
    closes_from_frames,
)
from signal_engine.validation import SignalValidationResult, SignalValidator

__all__ = [
    "CandidateRule",
    "DirectionCandidate",
    "FeatureIntakePayload",
    "IndicatorComputationError",
    "LLMInsightProvider",
    "MACDResult",
    "MLPredictionProvider",
    "MarketIntakeFrame",
    "RSIMACDRule",
    "RiskBindingProvider",
    "SignalAssembler",
    "SignalAssemblyError",
    "SignalAssemblyRequest",
    "SignalEngineError",
    "SignalIntakeError",
    "SignalLLMAttachmentError",
    "SignalLifecycleService",
    "SignalMLAttachmentError",
    "SignalNotFoundError",
    "SignalRecord",
    "SignalRegistrationError",
    "SignalRegistry",
    "SignalRiskAttachmentError",
    "SignalRuleError",
    "SignalValidationError",
    "SignalValidationResult",
    "SignalValidator",
    "SnapshotIntakeRef",
    "StubLLMInsightProvider",
    "StubMLPredictionProvider",
    "StubRiskBindingProvider",
    "apply_candidate",
    "assert_directional_confidence",
    "assert_safe_insight_text",
    "attach_confidence",
    "attach_invalidation",
    "attach_llm_insight",
    "attach_llm_insight_from_provider",
    "attach_ml_prediction",
    "attach_ml_prediction_from_provider",
    "attach_risk_assessment",
    "attach_risk_bindings",
    "attach_risk_bindings_from_provider",
    "build_invalidation_rule",
    "build_risk_assessment",
    "closes_from_frames",
    "compute_atr",
    "compute_macd",
    "compute_rsi",
    "compute_sma",
    "confidence_value_from_score",
    "ensure_llm_insight_present",
    "ensure_ml_prediction_present",
    "ensure_risk_bindings_present",
    "feature_intake_from_set",
    "feature_intake_from_store_record",
    "feature_intake_from_vector",
    "get_signal_registry",
    "invalidation_from_atr",
    "invalidation_from_structure",
    "llm_insight_from_llm_response",
    "llm_insight_from_parts",
    "market_intake_from_candle",
    "market_intake_from_record",
    "ml_prediction_from_inference_response",
    "ml_prediction_from_normalized_output",
    "provenance_from_intake",
    "reset_signal_registry",
    "snapshot_ref_from_snapshot",
]
